version: "3.4"

services:
  apigateway:
    build:
      context: ./SysChatBot
      dockerfile: SysChatBot.API/Dockerfile

    ports:
      - "5001:8080"

  authenticationservice:
    build:
      context: ./SysChatBot
      dockerfile: AuthenticationService/Dockerfile

  chatservice:
    build:
      context: ./SysChatBot
      dockerfile: ChatService/Dockerfile

  # logchatservice:
  #   build:
  #     context: ./SysChatBot # Set build context to the SysChatBot folder
  #     dockerfile: LogChatService/Dockerfile # Path to the Dockerf
  #   ports:
  #     - "5002:80"

  # grpcservice:
  #   build:
  #     context: ./gRPCService
  #   ports:
  #     - "5003:50051"
