version: '3.4'

services:
  apigateway:
    build:
      context: ./SysChatBot.API
    ports:
      - "5000:80"
  chatservice:
    build:
      context: ./ChatService
    ports:
      - "5001:80"
  logchatservice:
    build:
      context: ./LogChatService
    ports:
      - "5002:80"
  grpcservice:
    build:
      context: ./gRPCService
    ports:
      - "5003:50051"
